package com.atifstudios.store.carts;

import com.atifstudios.store.products.ProductNotFoundException;
import com.atifstudios.store.products.Product;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.UUID;

@Getter
@Setter
@Entity
@Table(name = "carts")
public class Cart {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id")
    private UUID id;

    @Column(name = "date_created", insertable = false, updatable = false) // insertable and updatable is set because the value is generated by database
    private LocalDate dateCreated;

    @OneToMany(mappedBy = "cart", cascade = {CascadeType.MERGE, CascadeType.REMOVE}, fetch = FetchType.EAGER, orphanRemoval = true)
    private Set<CartItem> items = new LinkedHashSet<>();

    public BigDecimal getTotalPrice() {
        return items.stream()
                .map(CartItem::getTotalPrice) // this will give a list of total of each item like [10,20,30]
                .reduce(BigDecimal.ZERO, BigDecimal::add); // this will start with zero and then Add each mapped price
    } // method ends

    public CartItem getCartItemByProductId(Long productId) {
        // finding the product by id in cart
        return items.stream()
                .filter(i -> i.getProduct().getId().equals(productId))
                .findFirst()
                .orElse(null);
    } // method ends

    public CartItem addOrUpdateCartItem(Product product) {
        // checking if product exist in the cart
        var cartItem = getCartItemByProductId(product.getId());
        if (cartItem != null) { // if it's not null, that means the same product is already exists in the cart
            cartItem.setQuantity(cartItem.getQuantity() + 1);
        } else {
            cartItem = new CartItem(); // creating new cart item
            cartItem.setProduct(product); // to associate with product entity (relational data)
            cartItem.setQuantity(1);
            cartItem.setCart(this); // to associate with cart entity (relational data)
            items.add(cartItem); // adding new product to cart
        }
        return cartItem;
    } // method ends

    public void removeCartItem(Long productId) {
        var cartItem = getCartItemByProductId(productId);
        if (cartItem != null) {
            items.remove(cartItem); // removing cartItem from cart
            cartItem.setCart(null); // removing cart association from cartItem
        } else {
            throw new ProductNotFoundException();
        }
    } // method ends

    public void clearCart() {
        items.clear();
    } // method ends

    public boolean isEmpty() {
        return items.isEmpty();
    } // end

} // class ends